[WIP] Spacelift

diff --git a/.github/workflows/spacelift.yml b/.github/workflows/spacelift.yml
--- a/.github/workflows/spacelift.yml
+++ b/.github/workflows/spacelift.yml
@@ -14,7 +14,7 @@ jobs:
 
       - name: Attempt to create versions for all modules with full debugging
         run: |
-          module_id = "terraform-spacelift-stack"
-          if ! spacectl module create-version --id $module_id; then
-            echo "Error encountered while creating version for module $module_id. Ignoring and continuing."
+          export MODULE="terraform-spacelift-stack"
+          if ! spacectl module create-version --id $MODULE; then
+            echo "Error encountered while creating version for module $MODULE. Ignoring and continuing."
           fi
